version: "3.9"

services:
  backend:
    build: ./backend
    container_name: vd-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: vd-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
