version: "3.9"

services:
  backend:
    build: ./backend
    container_name: vd-backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: vd-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
