services:
  - type: web
    name: vehicle-detector-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: vehicle_detector_New
      - key: MISTRAL_API_KEY
        sync: false
