services:
  # Backend API Service
  - type: web
    name: vehicle-detector-api
    runtime: python
    region: oregon  # Change to your preferred region
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: MONGO_URL
        sync: false  # ⚠️ Set manually in Render Dashboard
      - key: DB_NAME
        value: vehicle_detector_New

  # Frontend Service
  - type: web
    name: vehicle-detector-frontend
    runtime: static
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://vehicle-detector-api.onrender.com
